allowBuilds:
  "@reown/appkit": true
  bigint-buffer: true
  bufferutil: true
  canvas: false
  core-js: true
  es5-ext: true
  keccak: true
  protobufjs: true
  secp256k1: true
  sharp: true
  tiny-secp256k1: true
  unrs-resolver: true
  utf-8-validate: true
